<a href="https://colab.research.google.com/github/mirrormouse/machine_learning/blob/main/english_words.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

アルファベットと数字の変換準備（主観で母音->子音->あんまり使わないやつに並べた）

In [29]:
import random
char="aiueomnhygrlbcdfkpstvwzxjq"
dic={}
for i in range(len(char)):
  dic[char[i]]=i
print(dic['c'])


13


ドライブをインポート

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


でたらめな５文字からなる英単語もどきを生成。これを数値に変換
例）["aiueq",...]->[[0,1,2,3,25],...]

In [38]:
def generate(data_size=1814,length=5):
  random_list=[]
  random_words=[]
  for i in range(data_size):
    word=''
    num=[]
    for j in range(length):
      a=random.randrange(26)
      c=char[a]
      word+=c
      num.append(a)
    random_list.append(num)
    random_words.append(word)
  return random_list,random_words

lists,word=generate(data_size=1814)
print(lists[:100])

[[19, 14, 23, 22, 4], [4, 20, 10, 16, 7], [13, 8, 13, 11, 12], [5, 25, 11, 23, 25], [1, 20, 0, 21, 10], [16, 20, 3, 20, 11], [0, 24, 20, 2, 22], [9, 2, 15, 3, 16], [10, 11, 4, 9, 5], [15, 8, 17, 7, 25], [2, 24, 10, 18, 22], [0, 14, 18, 21, 6], [2, 10, 20, 6, 22], [13, 4, 14, 10, 5], [25, 16, 10, 21, 12], [23, 1, 12, 2, 22], [5, 14, 4, 18, 5], [21, 18, 11, 4, 1], [9, 22, 4, 21, 22], [0, 10, 15, 24, 10], [20, 21, 6, 9, 21], [11, 22, 14, 7, 18], [14, 21, 18, 25, 18], [2, 25, 12, 19, 19], [17, 14, 5, 9, 14], [14, 6, 7, 13, 0], [7, 0, 8, 10, 13], [3, 19, 20, 24, 17], [4, 22, 5, 12, 20], [16, 19, 13, 1, 7], [20, 15, 5, 4, 23], [8, 20, 19, 14, 25], [5, 2, 5, 20, 2], [19, 4, 16, 8, 14], [4, 6, 9, 25, 6], [9, 0, 15, 6, 15], [15, 19, 1, 13, 21], [15, 22, 14, 12, 9], [24, 16, 25, 9, 12], [3, 16, 10, 19, 21], [7, 2, 10, 21, 17], [4, 16, 24, 17, 1], [10, 8, 1, 6, 19], [7, 5, 5, 23, 15], [0, 15, 21, 6, 10], [9, 25, 15, 12, 9], [7, 16, 23, 0, 14], [13, 4, 20, 8, 1], [13, 23, 3, 4, 9], [2, 13, 3, 2, 2

英文データの読み込み

In [35]:
base='drive/MyDrive/ML/train/'
f = open(base+'train.txt', 'r')
rawdata = f.read()
data=rawdata.split()
print(data)
f.close()

['The', 'two', 'submarines', 'of', 'the', 'U-1', 'class,', 'U-1', 'and', 'U-2,', 'were', 'built', 'for', 'the', 'Austro-Hungarian', 'Navy.', 'Constructed', 'according', 'to', 'an', 'American', 'design,', 'they', 'were', 'launched', 'in', '1909.', 'A', 'diving', 'chamber,', 'wheels', 'for', 'traveling', 'along', 'the', 'seabed,', 'and', 'other', 'experimental', 'features', 'were', 'tested', 'extensively', 'in', 'sea', 'trials.', 'Their', 'gasoline', 'engines', 'were', 'replaced', 'around', 'the', 'start', 'of', 'World', 'War', 'I', 'over', 'safety', 'and', 'efficiency', 'concerns.', 'The', 'boats', 'have', 'been', 'described', 'by', 'naval', 'historians', 'as', 'obsolete', 'by', 'the', 'time', 'they', 'were', 'commissioned', 'in', '1911.', 'Both', 'submarines', 'were', 'mobilized', 'briefly', 'during', 'the', 'Balkan', 'Wars,', 'and', 'otherwise', 'served', 'as', 'training', 'boats', 'before', '1915.', 'From', '1915', 'to', '1918', 'they', 'conducted', 'reconnaissance', 'cruises', 'out'

５文字の長さの英単語だけを大量に抽出し、まとめる。これも数値に変換。

In [108]:
import re
def correct_generate(data_size=10000,length=5):
  alpha_data=[]
  for word in data:
    word=word.lower()
    res = re.sub(r'[^a-zA-Z]', '', word)
    if len(res)==length:
      alpha_data.append(res)

  beta_data=[]
  for word in alpha_data:
    num=[]
    for id in range(len(word)):
      c=word[id]
      num.append(dic[c])
    beta_data.append(num)
  size=len(alpha_data)
  return alpha_data, beta_data, size

alpha,beta,_=correct_generate()
print(beta)

[[13, 11, 0, 18, 18], [12, 2, 1, 11, 19], [0, 11, 4, 6, 9], [4, 19, 7, 3, 10], [19, 7, 3, 1, 10], [18, 19, 0, 10, 19], [21, 4, 10, 11, 14], [12, 4, 0, 19, 18], [6, 0, 20, 0, 11], [12, 4, 0, 19, 18], [3, 6, 3, 5, 8], [15, 11, 3, 3, 19], [19, 7, 3, 18, 3], [6, 3, 21, 11, 8], [18, 19, 0, 19, 3], [18, 3, 10, 12, 18], [0, 20, 4, 1, 14], [18, 7, 1, 17, 18], [16, 6, 4, 21, 6], [6, 4, 10, 19, 7], [5, 0, 24, 4, 10], [5, 1, 6, 4, 10], [5, 1, 11, 3, 18], [19, 7, 1, 10, 14], [19, 4, 19, 0, 11], [0, 10, 3, 0, 14], [6, 4, 10, 19, 7], [18, 4, 2, 19, 7], [19, 7, 1, 10, 14], [21, 4, 10, 11, 14], [6, 4, 10, 19, 7], [11, 3, 0, 18, 19], [8, 3, 0, 10, 18], [12, 3, 9, 0, 6], [0, 11, 4, 6, 9], [13, 4, 0, 18, 19], [9, 10, 3, 0, 19], [21, 7, 1, 13, 7], [12, 3, 9, 0, 6], [6, 4, 10, 19, 7], [11, 3, 9, 0, 11], [2, 6, 19, 1, 11], [13, 1, 20, 1, 11], [21, 4, 10, 11, 14], [21, 4, 10, 11, 14], [17, 4, 21, 3, 10], [21, 4, 10, 11, 14], [2, 6, 1, 4, 6], [18, 17, 0, 13, 3], [15, 1, 10, 18, 19], [3, 6, 14, 3, 14], [19, 7,

訓練データの生成（上で作った２つを繋げるだけ）

In [72]:
x_train_list=lists+beta
y_train_list=[]
for i in range(len(lists)):
  y_train_list.append(0)
for i in range(len(beta)):
  y_train_list.append(1)

訓練データのリストをnumpyに変換。正解ラベルを生成

In [73]:
import numpy as np
x_train=np.array(x_train_list)
y_train=np.array(y_train_list)
print(x_train,y_train)

[[19 14 23 22  4]
 [ 4 20 10 16  7]
 [13  8 13 11 12]
 ...
 [ 8  1  3 11 14]
 [ 8  4  2  6  9]
 [ 8  4  2 19  7]] [0 0 0 ... 1 1 1]


ディープラーニングモデルを作る

In [84]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
model_1 = tf.keras.Sequential(name='my_model')
model_1.add(tf.keras.layers.Flatten(input_shape=(5,), name='flatten_layer_1'))
model_1.add(tf.keras.layers.Dense(128, activation='relu'))
model_1.add(tf.keras.layers.Dropout(0.2))
model_1.add(tf.keras.layers.Dense(128, activation='relu'))
model_1.add(tf.keras.layers.Dropout(0.2))
model_1.add(tf.keras.layers.Dense(128, activation='relu'))
model_1.add(tf.keras.layers.Dropout(0.2))
model_1.add(tf.keras.layers.Dense(128, activation='relu'))
model_1.add(tf.keras.layers.Dropout(0.2))
model_1.add(tf.keras.layers.Dense(128, activation='relu'))
model_1.add(tf.keras.layers.Dropout(0.2))
model_1.add(tf.keras.layers.Dense(128, activation='relu'))
model_1.add(tf.keras.layers.Dropout(0.2))
model_1.add(tf.keras.layers.Dense(2, activation='softmax'))

model_1.summary()

Model: "my_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_layer_1 (Flatten)    (None, 5)                 0         
_________________________________________________________________
dense_18 (Dense)             (None, 128)               768       
_________________________________________________________________
dropout_11 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_19 (Dense)             (None, 128)               16512     
_________________________________________________________________
dropout_12 (Dropout)         (None, 128)               0         
_________________________________________________________________
dense_20 (Dense)             (None, 128)               16512     
_________________________________________________________________
dropout_13 (Dropout)         (None, 128)               0  

モデルのコンパイル

In [85]:
model_1.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

学習！

In [86]:
history = model_1.fit(x_train, y_train, batch_size=1000, epochs=100,
                    validation_split=0.1)

Epoch 1/100
4/4 [==============================] - 1s 75ms/step - loss: 0.7902 - accuracy: 0.5289 - val_loss: 0.6751 - val_accuracy: 0.6198
Epoch 2/100
4/4 [==============================] - 0s 24ms/step - loss: 0.6853 - accuracy: 0.5617 - val_loss: 0.7494 - val_accuracy: 0.2645
Epoch 3/100
4/4 [==============================] - 0s 27ms/step - loss: 0.6631 - accuracy: 0.5715 - val_loss: 0.8473 - val_accuracy: 0.0358
Epoch 4/100
4/4 [==============================] - 0s 28ms/step - loss: 0.6491 - accuracy: 0.5770 - val_loss: 0.7858 - val_accuracy: 0.2948
Epoch 5/100
4/4 [==============================] - 0s 25ms/step - loss: 0.6362 - accuracy: 0.5997 - val_loss: 0.7109 - val_accuracy: 0.5152
Epoch 6/100
4/4 [==============================] - 0s 24ms/step - loss: 0.6154 - accuracy: 0.6337 - val_loss: 0.6949 - val_accuracy: 0.5730
Epoch 7/100
4/4 [==============================] - 0s 25ms/step - loss: 0.6010 - accuracy: 0.6576 - val_loss: 0.6936 - val_accuracy: 0.6061
Epoch 8/100
4/4 [===

In [101]:
def nothing_val(word):#元データ内にその単語が存在するか確認
  for w in alpha:
    if word==w:
      return False
  return True
nothing_val('blade')

True

In [99]:
def word2num(word):
  num=[]
  for id in range(len(word)):
    num.append(dic[word[id]])
  return num
def num2word(nums):
  word=''
  for i in nums:
    word+=char[i]
  return word
print(num2word([12, 3, 0, 18, 19]))
print(word2num("beast"))

beast
[12, 3, 0, 18, 19]


テスト

In [110]:
test_words=["beast","blade","shddf","adjsa"]
y_test=[1,1,0,0]
x_test=[]
for word in test_words:
  num=word2num(word)
  x_test.append(num)

test_loss, test_acc = model_1.evaluate(x_test, y_test, verbose=0)
print(test_loss)
print(test_acc)
predictions = model_1.predict(x_test)
print(predictions)

0.04766419902443886
1.0
[[0.07801969 0.92198026]
 [0.06646299 0.93353707]
 [0.98020303 0.01979694]
 [0.9795567  0.02044335]]


In [129]:
randomlist,randomword=generate(data_size=300000)
r_pred=model_1.predict(randomlist)
item=[]
for i in range(len(r_pred)):
  res=[i,r_pred[i][0]]
  item.append(res)
item.sort(key=lambda item:item[1])

In [131]:
top=30
ans=[]
for i in range(top):
  id=item[i][0]
  ans.append([randomword[id],item[i][1]])
  print([randomword[id],item[i][1]])

['axaic', 0.051334687]
['ajabl', 0.05201237]
['ajiik', 0.053448316]
['ajiik', 0.053448316]
['axail', 0.053809475]
['iwaac', 0.0541633]
['azaik', 0.054410905]
['ataul', 0.054576315]
['ijaib', 0.05459246]
['awaeb', 0.0551941]
['adaag', 0.05522654]
['ixail', 0.055347003]
['iqacr', 0.055372324]
['aqael', 0.055384837]
['axafg', 0.055492993]
['aqiup', 0.055934507]
['ijabg', 0.05603107]
['aqiad', 0.056035113]
['axaef', 0.05616152]
['iqaub', 0.056484368]
['ataby', 0.056601558]
['aqafb', 0.057224784]
['azaob', 0.05754608]
['azagb', 0.058025137]
['flaxo', 0.058090407]
['aqaky', 0.05811206]
['blijo', 0.058158726]
['lruze', 0.058521673]
['iziaf', 0.05858904]
['izabg', 0.058601838]
